### PR TITLE
Update pipelines

### PR DESCRIPTION
**Pull request by yousifalraheem**
### Description
This PR updates the pipeline adding a missing step to run `npm test`. It also introduces 2 environments of the build using node versions `12` and `14`, the latter being the LTS.

### CODE REVIEW

**Review by kherP — DISMISSED** [review]

**Comment by kherP** [comment]
@yousifalraheem, do you mind to include beta branch in the pipeline so we can also release beta version?

**Comment by yousifalraheem** [comment]
If that's the path you've decided on, just create a branch called **beta** and it will be released as beta. Bear in mind, docs will only be published from **master** branch.

**Comment by kherP** [comment]
> If that's the path you've decided on, just create a branch called **beta** and it will be released as beta. Bear in mind, docs will only be published from **master** branch.

i don't think it will trigger the workflow for this repo as both workflows are only listening to master branch. Do you mind to create another PR for these pipeline changes by branching out from master so we can update the workflow for beta branch as well?

**Comment by yousifalraheem** [comment]
This PR depends on #529 to be merged first for the build to pass

**Comment by yousifalraheem** [comment]
@mario-subo Could you please look at this error message and let me know what might be the source of the issue?

```
    Expected: "mesec"
    Received: "month"


    > 195 |         expect(monthElement.querySelectorAll("option").item(0).innerHTML.toLowerCase()).toBe("mesec");
```

**Review by kherP — APPROVED** [review]

**Pull request merged**
