### PR TITLE
refactor(components): add forward ref

### PR DESCRIPTION
**Pull request by kherP**
add forward ref to all components as spreaded ref is not allowed in function component

TODO
------
- [x] forward ref for notification
- [x] forward ref for toggle selector

### CODE REVIEW

**Comment by mario-subo** [comment]
We will revisit this PR when we have a stable new version. Marking it as wont fix for now

**Comment by yousifalraheem** [comment]
Technically this is a bug fix, without this PR, the users won't be able to get `ref` from components. Consider adding this BEFORE the major release.

**Review by yousifalraheem — APPROVED** [review]
Technically this is a bug fix, without this PR, the users won't be able to get `ref` from components. Consider adding this BEFORE the major release.

**Pull request merged**
