### PR TITLE
Feature/move dynamic form to lib

### PR DESCRIPTION
**Pull request by mario-subo**
moved the docs only custom hook to be used as a hook exposed by the library itself instead

### CODE REVIEW

**Review by kherP — APPROVED** [review]
@mario-subo , if not mistaken, in useDynamicForm, there is console.log which should be removed. i might be wrong, but i remember seeing the log when i test the documentation

**Comment by mario-subo** [comment]
> @mario-subo , if not mistaken, in useDynamicForm, there is console.log which should be removed. i might be wrong, but i remember seeing the log when i test the documentation

Yes, you're right! thanks! I removed it

**Review by kherP — APPROVED** [review]

**Pull request merged**
