### PR TITLE
New slider design

### LINKED ISSUE #108: New slider design
**Is your feature request related to a problem? Please describe.**
The slider visual looks too big and some users gets confused by the chevrons. Remake the design.

**Describe the solution you'd like**
Design Library Team (Leopold Roos, Henrik Hoglund & Jessi Nygren Walhed decided on this, with apporval of Ulrika Dettner- Larsson) have made this changes:
* 24x24px thumb.
* Remove both thumb chevrons.
* 4px hight on bar, with rounded corners.
Slider

**Describe alternatives you've considered**
* Round thumb like most others.
* Colored bar.

**Additional context**

### PR DESCRIPTION
**Pull request by EldRoos**
fixes #108 

Made thumb smaller square and removed chevrons, made bar thinner and adjusted width and rounded corners, prettify.

### CODE REVIEW

**Comment by yousifalraheem** [comment]
### Thank you for taking the time to contribute to our components library
Looks good to me even though I don't like the changes `prettier` is making, in some cases, it makes the code less readable. Maybe we should set up prettier rules to make it more readable.

Please make sure you mention this keyword `fixes #{issueNumber}` in the pull request description so it can be automatically closed when we merge the pull request. I already put it for this pull request. You can read more about [Closing issues using keywords](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords).

- [ ] This pull request is pending for the new design to be updated in [slider's page](https://designlibrary.sebgroup.com/components/slider/) of the design library

**Comment by EldRoos** [comment]
See prettier comment here:
https://github.com/sebgroup/react-components/issues/86#issuecomment-579821661

**Comment by EldRoos** [comment]
Could be a good idea to have both for a while. Maybe always do like that when things change much. Most other libraries keep depricated stuff for a few versions.

**Comment by mario-subo** [comment]
closing this PR ... see re #164

**Pull request closed without merging**
